spring.application.name=swp-dna-genx
spring.config.import=optional:dotenv:
google.client.id=443615178916-5p9djk25jon368lljhovev11s40p19j1.apps.googleusercontent.com
google.client.secret=${GOOGLE_CLIENT_SECRET}
google.redirect.uri=${GOOGLE_REDIRECT_URI}
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
jwt.refresh-expiration=604800000

### Database config
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
