spring.application.name=swp-dna-genx
google.client.id=443615178916-5p9djk25jon368lljhovev11s40p19j1.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:8080/api/v1/auth/oauth2/callback/google

jwt.secret=your_jwt_secret_key
jwt.expiration=3600000